### ISSUE TITLE
With no public personal GitHub repos, dialog still says “Choose repos to add”+“Add” [3]

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/build.snapcraft.io#422] opened 2017-03-07 10:56 UTC
0\. Set up a GitHub account with no public, personal repos in it, unless you have a spare one handy.
1\. Go to build.snapcraft.io and get started using this account.

What you see: The “Add” dialog still says “Choose repos to add” and has an “Add” button, despite offering no repos to choose from.

![empty add dialog](https://cloud.githubusercontent.com/assets/19801137/23653491/acbf73ba-0324-11e7-92f8-5e3d1655c0b5.jpg)

[What you should see](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q): “Hmm, nothing to see here… // The GitHub account {GitHub ID} doesn’t seem to be admin for any public repos. // • Want to use a private repo? Sign up and we’ll e-mail you…”

![choose repos to add - none available](https://cloud.githubusercontent.com/assets/19801137/25439928/bec0233c-2a95-11e7-9e67-7cc2a46b625a.png)

This issue will still be a problem, but will occur much less often, once organization repos (#132) and private repos (#537) are implemented.

**Comment by evandandrea** [comment] 2017-04-21 13:00
Now a duplicate of #657

**Comment by matthewpaulthomas** [comment] 2017-04-25 12:22
#657 is about the “My repos” list, whereas this is about the “Add repos” dialog.

**Comment by evandandrea** [comment] 2017-04-25 12:28
Ah, sorry about that!

**Comment by matthewpaulthomas** [comment] 2017-04-25 12:41
The mockup in the spec was already a bit out of date — the biggest change being that we’ll now need an e-mail address field, rather than using your U1/GitHub address, when signing up for notification of the implementations of organization and private repos.

Furthermore, with the introduction of organizations, we need to add two new suggestions: one for the possibility of repos where you have write but not admin permission, and one for the possibility of repos belonging to an organization that you haven’t given build.snapcraft.io access to (#680). And given that there’ll now be five suggestions, I don’t think we should use icons any more: they’d be numerous enough that they’d start looking like icons for repos rather than just decorative.

**Comment by matthewpaulthomas** [comment] 2017-04-26 14:34
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q).

**Comment by solazio** [comment] 2020-06-03 07:24
No relevant for snapcraft.io, closing

**Closed by solazio** 2020-06-03 07:24 UTC
Labels: Add repos, Priority: Medium
