### ISSUE TITLE
Snap collaborators can't connect GitHub repos to registered snaps

### ISSUE THREAD

**Issue by flexiondotorg** [canonical-web-and-design/build.snapcraft.io#1217] opened 2019-05-08 12:48 UTC
### Expected behaviour

A collaborator of a snap should be able to connect a GitHub repository to a registered snap.

### Steps to reproduce the problem

  * Create a "brand" store account. 
  * Register a snap name.
  * Add a collaborator to the snap.
  * As the collaborator try and connect https://snapcraft.io/build to the registered snap name.

### Specs

- _URL:_ http://snapcraft.io/build
- _Operating system:_  Ubuntu
- _Browser:_ Firefox

**Comment by bartaz** [comment] 2019-05-09 09:07
This is a known issue unfortunately. Never got scheduled for the fix because of other work in backlog.
Closing this one as a duplicate of #799.

**Closed by bartaz** 2019-05-09 09:07 UTC
