### ISSUE TITLE
Filterable list component

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/build.snapcraft.io#405] opened 2017-03-06 12:33 UTC
Comments:

@katie_fenn is it still valid? If not please move to done,Is this the same as search? And if not, how? https://trello.com/c/YEILhCOS

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/GgHar1iZ/81-filterable-list-component
Labels: Question,copy to github

**Comment by matthewpaulthomas** [comment] 2017-04-28 14:02
If this is filtering the “Add repos” dialog, it’s a duplicate of #330. Alternatively, it might be filtering the “My repos” list.

**Comment by solazio** [comment] 2020-06-03 07:22
No relevant for snapcraft.io, closing

**Closed by solazio** 2020-06-03 07:22 UTC
Labels: Priority: Low
