### ISSUE TITLE
Routes aren't tested

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/build.snapcraft.io#696] opened 2017-04-28 11:07 UTC
#695 was a regression that the test suite didn't catch (routes were being referenced that had been deleted).

**Comment by bartaz** [comment] 2017-04-28 11:49
Routes are tested (as separate entities), but the test for store route (test/routes/src/server/routes/t_store.js) was (obviously) removed when the handler was removed from code.

The issue is that we don't test whole server module (that imports the routes).
In given case probably simple test of trying to just run the server should fail on missing routes.

**Comment by solazio** [comment] 2020-06-03 08:39
Not relevant for snapcraft.io, closing

**Closed by solazio** 2020-06-03 08:39 UTC
Labels: Priority: Medium, Type: Technical debt
