### ISSUE TITLE
"report problems with ... this site" points to the old repository 

### ISSUE THREAD

**Issue by joedborg** [canonical-web-and-design/build.snapcraft.io#1235] opened 2019-09-24 16:15 UTC
## Summary

Currently points to https://github.com/canonical-websites/build.snapcraft.io/issues

## Screenshot

![Screenshot from 2019-09-24 12-13-52](https://user-images.githubusercontent.com/1426404/65529852-e943c600-dec4-11e9-9f06-522a1f0f05f3.png)

**Comment by solazio** [comment] 2020-06-02 14:34
@lilyvidenova can you please have a quick look at this

**Comment by lilyvidenova** [comment] 2020-06-02 14:45
Hm, I cannot reproduce this, I believe it's been fixed already - closing it

**Closed by lilyvidenova** 2020-06-02 14:45 UTC
Labels: Priority: Low
