### ISSUE TITLE
Delete repo fail

### ISSUE THREAD

**Issue by JackDandy** [canonical-web-and-design/build.snapcraft.io#1176] opened 2018-11-25 12:00 UTC
Two repos's were added inside build.snapcraft.io from a GitHub account that links an organizational release repo.

I want to delete one of the two repo's from the snap, but this is failing.

**Comment by bartaz** [comment] 2018-11-26 09:46
@JackDandy Can you give us more details about the error you are receiving? 

Can you make a screenshot of browser JS console when you try to delete the repo? What's the error there? 

Thanks!

**Comment by JackDandy** [comment] 2018-11-26 15:21
@bartaz ... Here's an anim gif of the failure ... https://vgy.me/35g81N.gif

**Comment by bartaz** [comment] 2018-11-27 12:15
@JackDandy Thanks for a video, that's helpful. Unfortunately I cannot reproduce the issue myself, and the timeout error that shows up for you doesn't tell much.

Is this the repo you want removed? https://github.com/JackDandy/SickGear 
I can try do to it manually.

**Comment by JackDandy** [comment] 2018-11-27 12:44
Yes please. 

Also, I would like SickGear to be the base snap url when it is made public, and for SickGear/SickGear repo to be used. I would also like that repo to auto build, but given SickGear is an org repo with no direct signin, then how do I set that up in GH settings for that org repo?

Thanks

**Comment by JackDandy** [comment] 2018-11-27 16:48
If this is going to take another 24 hrs, or if you have any other questions, then can we speed things up by  chatting in IRC/#snappy ?

**Comment by bartaz** [comment] 2018-11-27 19:47
@JackDandy Hi, sorry - I have some issues accessing our prod env to delete the repo. I'll try to sort it out tomorrow.

**Comment by bartaz** [comment] 2018-11-28 09:56
Sorry it takes so long. It seems that your repo is one of a bunch affected by a Launchpad bug (https://bugs.launchpad.net/launchpad/+bug/1803163)

It means that we will likely wont be able to delete it (either via build.snapcraft or manually in Launchpad) until it's fixed. I'll give it a try as it may success eventually, but for now I'm marking this issue blocked until LP bug is fixed.

**Comment by JackDandy** [comment] 2018-11-28 10:33
ugh, indefinite nightmare. 

thanks for the feedback.

**Comment by bartaz** [comment] 2018-11-28 10:39
@JackDandy But, issues around deleting this repo, shouldn't affect building the other one.

I'm not really sure what you meant here:

> Also, I would like SickGear to be the base snap url when it is made public, and for SickGear/SickGear repo to be used. I would also like that repo to auto build, but given SickGear is an org repo with no direct signin, then how do I set that up in GH settings for that org repo?

As far as I see you have SickGear/SickGear repo set up in BSI. By default repos added are built on every push to the repo, so no additional configuration should be needed.

**Comment by JackDandy** [comment] 2018-11-28 10:45
I merged on SickGear organisation account yesterday, and had to do a manual build in snap webui.

If I make the snap public, are the failed ones also public ? I want just snap/sickgear (SickGear) that is built from the org account (i.e. SickGear/SickGear @ github) to be public in the store.

**Comment by bartaz** [comment] 2018-11-28 10:54
If a build fails this revision of a snap is not published to the store (because it didn't build properly), so only successful builds are published in the store snap (edge channel).

Once they are published you can decide to promote them to any other channel (beta/candidate/stable).

**Comment by bartaz** [comment] 2018-11-28 10:58
@JackDandy OK. Not building on commit is a different issue - not sure why this may happening. My first guess is that maybe if you moved the repo the webhook that is set on GitHub is still old (refers to old repo location or has a secret generated for old repo). If that's the case you may need to remove the webhook manually, remove repo from build.snapcraft ,and add it again (to make sure webhook is recreated). 

If you notice that builds don't trigger on push or merge feel free to open a new issue here.

**Comment by JackDandy** [comment] 2018-11-28 12:12
Sure, thanks.

Final q: how do I set "verified" status, e.g. like "Plex" has ? Your systems have pulled the org repo, and it is clear to see already.

**Comment by bartaz** [comment] 2018-11-28 12:37
@JackDandy As far as I understand currently only a selected group of publishers got a Verified status, I don't know if there is any process to apply for it, but it's better to ask on forum: https://forum.snapcraft.io/t/how-to-become-verified-publisher/7442

**Comment by JackDandy** [comment] 2019-02-07 10:29
It's been over a couple months and no shift on this from LP. 

So, thinking from the side of Canonical, can you make it in the UI so that we can stop a repo from even being sent to LP. 

A **pause** button alongside the delete -- so that we don't have to wait so long for builds to complete that we don't care for (which is why the delete was attempted)

**Comment by Lin-Buo-Ren** [comment] 2019-03-13 05:53
I also encountered a similar problem, the request returned with 504 Gateway timeout.

This particular snap has been transferred to the upstream, I've removed the webhook at my repository at the GitHub end but buid.snapcraft.io still build the snap due to "dependency changed" build trigger and keep publishing invalid builds to the edge channel (which is differentiable due to the different versioning style)

**Comment by Lin-Buo-Ren** [comment] 2019-03-13 05:55
The snap in particular: https://github.com/Lin-Buo-Ren/gallery-dl-snap

Is there anything you can do from the backend until the bug is resolved?

**Comment by Lin-Buo-Ren** [comment] 2019-03-21 14:49
One possible workaround is to change the registered snap name to make it mismatch with the one specified in the Snapcraft recipe.

![Screenshot](https://user-images.githubusercontent.com/13408130/54760609-6139e680-4c2b-11e9-866a-2e12806f1df6.png)

**Comment by JackDandy** [comment] 2019-03-24 15:10
@Lin-Buo-Ren that's how i do my workaround too

**Comment by bartaz** [comment] 2019-04-03 14:39
Also reported in #1211

**Comment by kerolloz** [comment] 2019-04-11 10:53
@Lukewh 
![image](https://user-images.githubusercontent.com/36763164/55952018-d613a580-5c58-11e9-94eb-2495be138c9f.png)

**Comment by solazio** [comment] 2020-06-03 10:05
This is fixed in the `Builds` tab in snapcraft.io

**Closed by solazio** 2020-06-03 10:05 UTC
Labels: Blocked ⛔
