### ISSUE TITLE
Add snap login to by-revision install instructions

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/build.snapcraft.io#721] opened 2017-05-05 01:30 UTC
I think we should ask you to snap login (again) to work around current error messages being inaccurate:
```
$ sudo snap install --revision=17 bcc
error: cannot install "bcc": snap not found

$ sudo snap login
Email address: ev@ubuntu.com
Password of "ev@ubuntu.com": 
Two-factor code: 000000
Login successful

$ sudo snap install --revision=17 bcc
bcc 0.3.0-20170329-1737-26383f2 from 'ev' installed
```

**Comment by bartaz** [comment] 2017-06-05 09:24
Seems that #825 is related or even duplicate of this.

**Closed** 2020-06-11 10:36 UTC
Labels: Test instructions
