### ISSUE TITLE
"Built, failed to release" on supertuxkart

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/build.snapcraft.io#1225] opened 2019-06-12 16:19 UTC
## Summary

Supertuxkart successfully builds, but the UI reports "built, failed to release" for all architectures. This has been occurring for several weeks, to a couple months. This appears to currently happen with every build.

## Process

Manually trigger supertuxkart to build. Wait for the builds to finish and go through review. The reporting will state that the revisions are "failed to release" . This seems like a possible timeout issue, maybe due to the size of the supertuxkart snap.

## Current and expected result

The snap should correctly go through review and release, and the UI should then report the success.

## Screenshot

![image](https://user-images.githubusercontent.com/147548/59368276-df2dfb00-8d0b-11e9-9120-197315bc8b22.png)

![image](https://user-images.githubusercontent.com/147548/59368442-3d5ade00-8d0c-11e9-87ce-503a67d731ea.png)

**Comment by matthewpaulthomas** [comment] 2019-06-17 08:00
That you’re guessing what the cause might be, and you haven’t mentioned or screenshotted the build page, suggests that you aren’t aware of the pages for individual builds. Try clicking any of the “Built, failed to release” cells, and you’ll go to a page that has an error message and build log.

I’ve just reported #1226 that the links aren’t obvious.

**Comment by therealjuan** [comment] 2019-06-17 10:06
Apart from the visual style of links, the real problem is that there is no connection between builds and releases. We are working towards merging both areas in this cycle and we could get on to fix this problem (among others) soon.

Leaving this item in our backlog once we start integrating build.snapcraft.io with snapcraft.io

Stay tuned for updates and hope you are back and settled at home after the summit :)

**Comment by diddledan** [comment] 2019-06-17 12:05
> That you’re guessing what the cause might be, and you haven’t mentioned or screenshotted the build page, suggests that you aren’t aware of the pages for individual builds. Try clicking any of the “Built, failed to release” cells, and you’ll go to a page that has an error message and build log.

You've made an incorrect assumption there. I am aware of the build logs. The reason I didn't screenshot or copy text from them is because they aren't showing anything useful:

```plain
cmake --build . -- -j4
cmake --build . --target install
Staging alsa 
Staging desktop-glib-only 
Skipping stage libopenh264-library (already ran)
Skipping stage libopenglrecorder (already ran)
Staging libopenh264-helper 
Staging supertuxkart 
Priming alsa 
Priming desktop-glib-only 
Priming libopenh264-library 
Priming libopenglrecorder 
Priming libopenh264-helper 
Priming supertuxkart 
The 'icon' property is specified in adopted info as well as the YAML: taking the property from the YAML
Snapping 'supertuxkart' ...

Snapped supertuxkart_1.0_amd64.snap
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=bionic --arch=amd64 SNAPBUILD-584612
Scanning for processes to kill in build SNAPBUILD-584612
```

**Comment by matthewpaulthomas** [comment] 2019-06-17 16:15
I’m glad to have guessed wrong! On the build page, any “Build failed to release” heading is supposed to be followed by an explanation, for example:

![release-failed-2](https://user-images.githubusercontent.com/19801137/59617835-f6f7eb80-911e-11e9-991e-bde8e3426e75.png)

![release-failed-1](https://user-images.githubusercontent.com/19801137/59617836-f7908200-911e-11e9-95c7-25bc4cbbe174.png)

So at the least, it’s a bug that no error message is showing here (even if it has to be a generic suggestion to try building and releasing manually). There might _also_ be a a bug in Snapcraft itself, that it fails to return an error message to begin with (as in [LP#1743587](https://launchpad.net/bugs/1743587) or [LP#1627865](https://launchpad.net/bugs/1627865), for example).

What happens if you build the snap locally and use `snapcraft push`?

**Comment by cjwatson** [comment] 2019-06-17 16:32
It can't be a bug in snapcraft, because Launchpad doesn't use snapcraft to do the push and release (for various reasons not relevant here), but rather its own implementation of the same fairly simple HTTP transactions.  Also, the failure in this case is in the analogue of the `snapcraft release` step, not the `snapcraft push` step.

**Comment by johanneswilm** [comment] 2019-12-07 11:02
For fiduswriter this also happens, but seemingly at random and not always for the same architectures. Yet it seems that they can still be released to the store and at least the one I tested also ran. Is there consequence of the fail of release? Or can it safely be ignored?

**Comment by solazio** [comment] 2020-06-02 14:21
This is fixed in the `Builds` tab on snapcraft.io

**Closed by solazio** 2020-06-02 14:21 UTC
Labels: Priority: Medium
