### ISSUE TITLE
Don't jump scroll down on repo screen

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#1124] opened 2018-06-14 09:03 UTC
## Summary

When I click on a repo I almost always want to see the latest build. When I click though, I get jumped half way down the page which is quite infuriating because I never want that.

## Process

Login to build and find a snap I want to inquire about. (in this case gitter-desktop)

![screenshot from 2018-06-14 10-02-18](https://user-images.githubusercontent.com/1841272/41402480-502282d8-6fba-11e8-8acd-458d19a92ebc.png)

Click on the repo.

## Current and expected result

I get to the gitter-desktop page, but scrolled down.

![screenshot from 2018-06-14 10-03-10](https://user-images.githubusercontent.com/1841272/41402487-54b93828-6fba-11e8-9d99-87bb1ca79542.png)

This is what I actually want to see.

![screenshot from 2018-06-14 10-03-36](https://user-images.githubusercontent.com/1841272/41402497-58c21e08-6fba-11e8-8d3c-277ac761f7c7.png)

**Comment by matthewpaulthomas** [comment] 2018-06-20 09:01
Try this:

1. Go to the “Repos to build” page and scroll to the top.
2. Click any repo link you can see without scrolling. You end up at the top of the page for that repo.
3. Click any build link you can see without scrolling. You end up at the top of the page for that build.

4. Return to the “Repos to build” page and scroll down _Z_ pixels.
5. Click any repo link you can see without scrolling. You end up _Z_ pixels down from the top of the page for that repo.
6. Click any build link you can see without scrolling. You end up _Z_ pixels down from the top of the page for that build.

So I think these “pages” aren’t separate HTML pages, they’re just chunks of HTML that are being squirted into (and later removed from) a single page, with URL changes provided by JS. The browser doesn’t know that it’s on a new “page” (URL change notwithstanding), so it doesn’t know it should scroll to the top, so it just stays where it is, which looks like it’s jumped down.

We could just scroll you to the top whenever changing the URL. But that would make you lose your place when you clicked Back to return to a long list of repos/builds.

If so, then two other ways of fixing this:
a. Return to serving separate HTML pages for each “page”.
b. Reimplement browsers’ behavior of recording the scroll position of each “page” just before you leave, then restoring it if/when you return via Back/Forward (but not if you return by clicking a link).

**Comment by cjwatson** [comment] 2018-06-20 09:16
Unfortunately there is no "return to serving ..."; BSI was designed from the start to be a single-page application.  (In fact, it was essentially given as a requirement.)  One of the fundamental problems with SPAs is that they intrinsically have to reimplement all this stuff that the browser ordinarily gives you for free.

Perhaps something like [react-router-scroll](https://www.npmjs.com/package/react-router-scroll) would be useful here?  Its documentation at least suggests it'd be the right thing for us.

**Comment by bartaz** [comment] 2018-06-20 09:29
Yes, this is quite known issue in single page apps. As suggested by @cjwatson `react-router-scroll` or similar solution should fix that.

**Comment by solazio** [comment] 2020-06-01 15:26
This is fixed now in the new `Builds` tab on snapcraft.io

**Closed by solazio** 2020-06-01 15:26 UTC
Labels: Priority: Medium
