### ISSUE TITLE
"Invalid signature" when signing into SSO Win10/IE11

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/build.snapcraft.io#552] opened 2017-03-28 09:11 UTC
Went through name registration, hit sign in, signed into SSO and added 2fa code (but got it wrong first time, so had to re-type it on the same page). Once I successfully entered my 2fa, I get bounced back to a screen with "Invalid signature" on it.

![screenshot 7](https://cloud.githubusercontent.com/assets/1841272/24397657/dfe9f406-139e-11e7-8a6a-ea9301721bb3.png)

**Comment by earnubs** [comment] 2017-03-28 09:27
Usually caused by OpenID association handle mismatch, check memcached stability on BSI side.

**Comment by cjwatson** [comment] 2017-03-28 11:45
@popey Does this happen every time in IE11?

Things I've looked at so far:

 * Both production memcached instances have been running since 2016-12-21, and I seem to be able to talk to both of them from both appserver units, so I don't think there's a memcached stability problem here.
 * There's not much interesting in the logs from this event: on the BSI side, I can see the requests to `/login/authenticate` and `/login/failed`, but nothing else; and on the SSO side, I can see the multiple passes through `+decide` and `two_factor_auth` and the redirection back to BSI, but there don't seem to be any associated errors.

So my theory at the moment is that there's some problem related to `crypto.createHmac` or similar on IE11, but knowing whether it happens every time or only sometimes would be useful.

**Comment by earnubs** [comment] 2017-03-28 11:56
I've completed SSO sign in twice on Win10/IE11 (via browserstack) without error.

**Comment by popey** [comment] 2017-03-28 12:34
@cjwatson I now can't reproduce it :(

**Comment by solazio** [comment] 2020-06-03 07:37
No relevant for snapcraft.io, closing

**Closed by solazio** 2020-06-03 07:37 UTC
Labels: Priority: Medium
